apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 295058252080.dkr.ecr.ap-northeast-1.amazonaws.com/frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_NAME
          value: eks-lesson
        - name: ON_EKS
          value: 'true'